version: '3.8'

services:
  bot:
    build: .
    container_name: bot_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - scheduler

  scheduler:
    build:
      context: ./services/scheduler
      dockerfile: Dockerfile
    container_name: scheduler_container
    volumes:
      - ./services/scheduler:/app
    command: ["python", "schedule.py"]